tables:
  species:
    label: Species
    id: SpecCode
    columns:
      [
        SpecCode,
        Genus,
        Species,
        FamCode,
        FBname,
        Length,
        Aquarium,
        Fresh,
        Saltwater,
      ]

  families:
    label: Family
    id: FamCode
    columns: [FamCode, Family]
